# Branches that trigger a build on commit

jobs:
- job: Do_Some_Stuff
  pool:
    name: NetCorePublic-Pool
    queue: BuildPool.Windows.10.Amd64.Open

  timeoutInMinutes: 10

  steps:
    - task: PowerShell@2
      displayName: Enable cross-org publishing
      inputs:
        filePath: .\enable-cross-org-publishing.ps1
        arguments: -token testValueForLoggingPurposes

    - script: .\doStuff.cmd
      displayName: Do the thing we're experimenting with v1.

    - task: PowerShell@2
      displayName: Enable cross-org publishing
      inputs:
        filePath: .\enable-cross-org-publishing-arcade.ps1
        arguments: -token testValue2ForLoggingPurposes

    - script: .\doStuff.cmd
      displayName: Do the thing we're experimenting with v2.
